<a href="https://colab.research.google.com/github/ashishkarnn/PW_EDA_ASSIGNMENT/blob/main/Copy_of_Untitled22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?
#  NumPy is a library for numerical computing in Python that provides support for large, multi-dimensional arrays and matrices, and a wide range of mathematical functions. It enhances Python's capabilities by enabling vectorized operations, reducing the need for loops, and increasing performance and memory efficiency.

In [ ]:
# 2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?
# . np.mean() computes the arithmetic mean along the specified axis, treating all elements equally. np.average() can compute a weighted average if weights are provided. Use np.mean() for simple average and np.average() when weights are involved.

In [ ]:
# 3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.
import numpy as np

arr1d = np.array([1, 2, 3, 4])
reversed_1d = arr1d[::-1]

arr2d = np.array([[1, 2], [3, 4], [5, 6]])
reversed_rows = arr2d[::-1, :]
reversed_columns = arr2d[:, ::-1]
reversed_both = arr2d[::-1, ::-1]

reversed_1d, reversed_rows, reversed_columns, reversed_both


(array([4, 3, 2, 1]),
 array([[5, 6],
        [3, 4],
        [1, 2]]),
 array([[2, 1],
        [4, 3],
        [6, 5]]),
 array([[6, 5],
        [4, 3],
        [2, 1]]))

In [ ]:
# 4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.
arr = np.array([1, 2, 3])
dtype = arr.dtype
dtype



dtype('int64')

In [ ]:
# 5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?
"""
An ndarray is a N-dimensional array object in NumPy that supports efficient operations on homogeneous data. Key features include fixed size, element-wise operations, slicing, broadcasting, and vectorization. Unlike Python lists, ndarrays store data in contiguous memory blocks, support element-wise operations, and are more efficient for numerical computations.
"""


'\nAn ndarray is a N-dimensional array object in NumPy that supports efficient operations on homogeneous data. Key features include fixed size, element-wise operations, slicing, broadcasting, and vectorization. Unlike Python lists, ndarrays store data in contiguous memory blocks, support element-wise operations, and are more efficient for numerical computations.\n'

In [ ]:
# 6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.
"""
NumPy arrays consume less memory, support vectorized operations which eliminate explicit loops, and use optimized C-backed functions. This leads to faster execution for large-scale numerical computations compared to Python lists.
"""


'\nNumPy arrays consume less memory, support vectorized operations which eliminate explicit loops, and use optimized C-backed functions. This leads to faster execution for large-scale numerical computations compared to Python lists.\n'

In [ ]:
# 7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.
a = np.array([1, 2])
b = np.array([3, 4])

vstacked = np.vstack((a, b))
hstacked = np.hstack((a, b))

vstacked, hstacked


(array([[1, 2],
        [3, 4]]),
 array([1, 2, 3, 4]))

In [ ]:
# 8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.
arr = np.array([[1, 2], [3, 4], [5, 6]])
flipped_lr = np.fliplr(arr)
flipped_ud = np.flipud(arr)

flipped_lr, flipped_ud


(array([[2, 1],
        [4, 3],
        [6, 5]]),
 array([[5, 6],
        [3, 4],
        [1, 2]]))

In [ ]:
# 9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?
arr = np.array([1, 2, 3, 4, 5])
split_arrs = np.array_split(arr, 3)
split_arrs


[array([1, 2]), array([3, 4]), array([5])]

In [ ]:
# 10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?
"""
Vectorization is the process of applying operations to entire arrays without explicit loops. Broadcasting allows operations on arrays of different shapes by automatically expanding them. Both improve efficiency and code clarity.
"""


'\nVectorization is the process of applying operations to entire arrays without explicit loops. Broadcasting allows operations on arrays of different shapes by automatically expanding them. Both improve efficiency and code clarity.\n'

In [ ]:
# pratical

In [ ]:
# 1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.
import numpy as np

arr = np.random.randint(1, 101, size=(3, 3))
transposed = arr.T
arr, transposed


(array([[23, 73, 62],
        [89, 77, 56],
        [72, 37, 49]]),
 array([[23, 89, 72],
        [73, 77, 37],
        [62, 56, 49]]))

In [ ]:
# 2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.
arr = np.arange(10)
reshaped_2x5 = arr.reshape(2, 5)
reshaped_5x2 = arr.reshape(5, 2)
reshaped_2x5, reshaped_5x2


(array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]]))

In [ ]:
# 3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.
arr = np.random.rand(4, 4)
bordered_arr = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
bordered_arr


array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.51353923, 0.00149813, 0.73335469, 0.92889036,
        0.        ],
       [0.        , 0.77254543, 0.01766208, 0.05512453, 0.51726127,
        0.        ],
       [0.        , 0.11133897, 0.64734429, 0.14316192, 0.25649086,
        0.        ],
       [0.        , 0.69294321, 0.50367813, 0.49939859, 0.93751771,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ]])

In [ ]:
# 4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.
arr = np.arange(10, 61, 5)
arr


array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60])

In [ ]:
# 5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.
arr = np.array(['python', 'numpy', 'pandas'])

upper = np.char.upper(arr)
lower = np.char.lower(arr)
title = np.char.title(arr)

upper, lower, title


(array(['PYTHON', 'NUMPY', 'PANDAS'], dtype='<U6'),
 array(['python', 'numpy', 'pandas'], dtype='<U6'),
 array(['Python', 'Numpy', 'Pandas'], dtype='<U6'))

In [ ]:
# 6. Generate a NumPy array of words. Insert a space between each character of every word in the array.
arr = np.array(['python', 'data', 'science'])
spaced = np.char.join(' ', arr)
spaced


array(['p y t h o n', 'd a t a', 's c i e n c e'], dtype='<U13')

In [ ]:
# 7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

add = a + b
sub = a - b
mul = a * b
div = a / b

add, sub, mul, div


(array([[ 6,  8],
        [10, 12]]),
 array([[-4, -4],
        [-4, -4]]),
 array([[ 5, 12],
        [21, 32]]),
 array([[0.2       , 0.33333333],
        [0.42857143, 0.5       ]]))

In [ ]:
# 8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.
identity = np.eye(5)
diagonal = np.diag(identity)
identity, diagonal


(array([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]]),
 array([1., 1., 1., 1., 1.]))

In [ ]:
# 9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.
arr = np.random.randint(0, 1001, size=100)

def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(np.sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True

prime_numbers = np.array([x for x in arr if is_prime(x)])
prime_numbers


array([839, 967, 139, 409, 157, 727, 521, 389, 607, 631, 607, 521, 773,
       863, 149,   2, 967])

In [ ]:
# 10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.
daily_temps = np.random.randint(15, 35, size=30)
weekly_averages = daily_temps.reshape(6, 5).mean(axis=1)
weekly_averages


array([25.6, 20.2, 23.6, 18.2, 25.4, 21.4])