<a href="https://colab.research.google.com/github/ashishkarnn/PW_EDA_ASSIGNMENT/blob/main/Numpy_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Basic**

NUMPY || PANDAS || MATPLOTLIB  || SEABORN || PLOTLY || BOOKEH

In [ ]:
# numpy >> numerical python

In [ ]:
import numpy as np # as : alias

In [ ]:
# Numpy store the data in numpy array
# An array is the container / data structure used to store data of same type >> homogenous data

In [ ]:
# Create a NumPy ndarray Object
import numpy as np
arr = np.array([1,2,3,4,5])

In [ ]:
print(arr)

[1 2 3 4 5]


In [ ]:
type(arr)

numpy.ndarray

In [ ]:
print(type(arr))

<class 'numpy.ndarray'>


In [ ]:
# 0-D Arrays

In [ ]:
import numpy as np
arr = np.array(42)
print(arr)

42


In [ ]:
# 1-D Arrays

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [ ]:
# 2-D Arrays

In [ ]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
# 3-D arrays

In [ ]:
import numpy as np
arr =  np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [ ]:
# Check Number of Dimensions?
# NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

In [ ]:
import numpy as np

a = np.array(42)
b = np.array([1,2,3,4,5,6])
c = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)

0


In [ ]:
print(b.ndim)

1


In [ ]:
print(c.ndim)

2


In [ ]:
print(d.ndim)

3


In [ ]:
# Higher Dimensional Arrays

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)


[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4], ndmin = 5)
print(arr)


[[[[[1 2 3 4]]]]]


In [ ]:
print('number of dimension :', arr.ndim)

number of dimension : 5


In [ ]:
# NumPy Array Indexing

In [ ]:
# Access Array Elements
import numpy as np
arr = np.array([1,2,3,4])

print(arr[0])

1


In [ ]:
print(arr[1])

2


In [ ]:
print(arr[2])
print(arr[3])

3
4


In [ ]:
sum = arr[2] + arr[3]

In [ ]:
print(sum)

7


In [ ]:
# Access 2-D Arrays

In [ ]:
# Access the element on the first row, second column:
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [ ]:
import numpy as np
arr = np.array([[1,2,3,4,5,6],[7,8,9,19,11,12]])
print('3rd element on 1st row :', arr[0,2])

3rd element on 1st row : 3


In [ ]:
# Access 3-D Arrays
# To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.

In [ ]:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2])

6


In [ ]:
# Negative Indexing
# Use negative indexing to access an array from the end.

import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Last element from 2nd dim:', arr[1,-1])

Last element from 2nd dim: 10


In [ ]:
# NumPy Array Slicing

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9])

In [ ]:
print(arr[1:5])

[2 3 4 5]


In [ ]:
print(arr[4:])

[5 6 7 8 9]


In [ ]:
print(arr[:4])

[1 2 3 4]


In [ ]:
# Negative Slicing : Use the minus operator to refer to an index from the end.
import numpy as np
arr = np.array([1,2,3,4,5,6,7])

In [ ]:
print(arr[-3:-1])

[5 6]


In [ ]:
# STEP : Use the step value to determine the step of the slicing.

In [ ]:
# Return every other element from index 1 to index 5
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5:2])

[2 4]


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[::2])

[1 3 5 7]


In [ ]:
# Slicing 2-D Arrays
import numpy as np
arr = np.array([[1,2,3,4,5,6,7],[8,9,10,19,13,12,14]])
print(arr[1,1:4])

[ 9 10 19]


In [ ]:
# NumPy Data Types
# strings - used to represent text data, the text is given under quote marks. e.g. "ABCD"
# integer - used to represent integer numbers. e.g. -1, -2, -3
# float - used to represent real numbers. e.g. 1.2, 42.42
# boolean - used to represent True or False.
# complex - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j
# i - integer
# b - boolean
# u - unsigned integer
# f - float
# c - complex float
# m - timedelta
# M - datetime
# O - object
# S - string
# U - unicode string
# V - fixed chunk of memory for other type ( void )


In [ ]:
import numpy as np
# Checking the Data Type of an Array

arr = np.array([1,2,3,4])
print(arr.dtype)

int64


In [ ]:
# Get the data type of an array containing strings
import numpy as np
arr = np.array(['x','y','z'])
print(arr.dtype)

<U1


In [ ]:
# Creating Arrays With a Defined Data Type
import numpy as np
arr = np.array([1,2,3,4,5],dtype = 'S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4' b'5']
|S1


In [ ]:
# NumPy Array Copy vs View

In [ ]:
# COPY
# Make a copy, change the original array, and display both arrays
# The copy SHOULD NOT be affected by the changes made to the original array.
import numpy as np
arr = np.array([1,2,3,4,5])
x = arr.copy()
arr[0] = 43
print(arr)
print(x)

[43  2  3  4  5]
[1 2 3 4 5]


In [ ]:
# VIEW
# Make a view, change the original array, and display both arrays
# The view SHOULD be affected by the changes made to the original array.
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [ ]:
# Make Changes in the VIEW
# Make a view, change the view, and display both arrays

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.view()
x[0] = 31
print(arr)

print(x)

[31  2  3  4  5]
[31  2  3  4  5]


In [ ]:
# As mentioned above, copies owns the data, and views does not own the data, but how can we check this?
# Every NumPy array has the attribute base that returns None if the array owns the data.
# Otherwise, the base  attribute refers to the original object.

import numpy as np
arr = np.array([1,2,3,4,5])
x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [ ]:
# NumPy Array Shape : The shape of an array is the number of elements in each dimension.
# NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.

In [ ]:
# Print the shape of a 2-D array
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)

(2, 4)


In [ ]:
# Create an array with 5 dimensions using ndmin using a vector with values 1,2,3,4 and verify that last dimension has value 4
import numpy as np
arr = np.array([1,2,3,4,5],ndmin = 5)
print(arr)
print("shape of the array:",arr.shape)

[[[[[1 2 3 4 5]]]]]
shape of the array: (1, 1, 1, 1, 5)


In [ ]:
# NumPy Array Reshaping
# Reshaping arrays
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
# Reshape From 1-D to 3-D
# Convert the following 1-D array with 12 elements into a 3-D array.
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
# NumPy Array Iterating
import numpy as np
arr = np.array([1,2,3])
for x in arr:
  print(x)

1
2
3


In [ ]:
# Iterating 2-D Arrays
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [ ]:
# If we iterate on a n-D array it will go through n-1th dimension one by one.

In [ ]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [ ]:
# Iterating 3-D Arrays
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [ ]:
# Iterate down to the scalars
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [ ]:
# Iterating Arrays Using nditer()
import numpy as np
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [ ]:
# Joining NumPy Arrays
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr = np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [ ]:
# Join two 2-D arrays along rows (axis=1)
import numpy as np
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]
